### ISSUE TITLE
Is it possible to save HAR automatically

### ISSUE THREAD

**Issue by stenalpjolly** [sonyseng/json-caching-proxy#7]
Is it possible to save HAR automatically?

**Comment by sonyseng** [comment]
@stenalpjolly Right now you have to make the GET request to `http://localhost:3001/proxy/har` in order to download the HAR file to your local machine. If you mean if it can save to the file system automatically, that's definitely doable. Right now the cache is in-memory. I'd welcome a PR if you have something.

**Comment by qur2** [comment]
I was also looking at doing something like that for my cypress test suite, but the problem is to know when to save, or at least when to stop writing to the file. I ended up with a bash script like that:
```bash
#!/bin/bash 

npx json-caching-proxy \
  -u http://localhost:8080 -p 8088 -l -a \
  --disablePlayback  &
child=$!

CYPRESS_BASE_URL=http://localhost:8088 npm run cypress:run
curl http://localhost:8088/proxy/har --silent --output ./cypress/fixtures/cypress-run.har.json

kill -15 "$child"
```

Basically it spawns the proxy on a different port as a background process. Then it runs the test suite on the proxy port. When it's done, it downloads the file and gently terminates the child process.

For replaying, you just need to feed the proxy with your har file, enable playback and remove the download step.

I hope this helps.

**Comment by sonyseng** [comment]
Closing really old issues
